### ISSUE TITLE
Authentication Failure  (pam-auth pam_auth_pass : Authentication failure)

### ISSUE THREAD

**Issue by pencilvania** [mmtaee/ocserv-users-management#32]
I have successfully installed ocserv on an Ubuntu 20.04 server using the provided install.sh script. However, I encountered an issue when attempting to create a user and log in. The server generates the following error message:

`pam-auth pam_auth_pass : Authentication failure`

This issue prevents users from authenticating and accessing the VPN server.

Steps to Reproduce:

Install ocserv on an Ubuntu 20.04 server using the install.sh script.
Create a user account using panel.
Attempt to log in with the newly created user account.
Observe the "Authentication failure" error.
Expected Behavior:
I expected to be able to create a user account and log in to the ocserv VPN server without encountering authentication errors.

Additional Information:

Operating System: Ubuntu 20.04
Installation Method: install.sh script provided with ocserv-users-management.
Any relevant logs or error messages should be included here for further diagnosis.
![image](https://github.com/mmtaee/ocserv-users-management/assets/8554101/a20e5fa8-73b4-44cd-954f-576306f990be)

**Comment by mmtaee** [comment]
The authentication of panel and ocserv is plain. you try to use pam authentication method.
the users will be store in file /etc/ocserv/ocpasswd and auth method is : auth="plain[passwd=/etc/ocserv/ocpasswd]"

try command below to create a test user in server:
`echo test\ntest\n | sudo ocpasswd -c /etc/ocserv/ocpasswd test`  
or try to create from pannel in http://YOUR_SERVER_IP in user tab

then try in client side to connect with command below:
` sudo openconnect -u test YOUR_IP_ADDRESS:OCSERV_PORT`
If there is an error, please report the bug, so that I can fix it.
After test remove user from panel or delete user from file /etc/ocserv/ocpasswd

**Comment by mmtaee** [comment]
This part is not Ocserv password. It is related to the password of the system administrator (sudo) .
